In [56]:
from functools import partial
from dask import delayed
import numpy as np
import dask.array as da
from dask.distributed import Client
import torch

In [35]:
client = Client(asynchronous=True)

/Users/thomassullivan/opt/anaconda3/envs/edgemont/lib/python3.9/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 49910 instead
  warnings.warn(


In [48]:
a0 = client.submit(lambda x: x(3), torch.ones)
a1 = await client.gather(a0)

In [50]:
a1

tensor([1., 1., 1.])

In [51]:
a2 = await client.submit(lambda x: x[1], a1)

In [54]:
a3 = await client.submit(lambda x: float(x[1]), a1)

In [55]:
a3

1.0

In [62]:
def set_value(a, index, value):
    a[index] = value
    return a

set_second_value = partial(set_value, index=2, value=2.0)

In [75]:
a1[2] = 2.0

In [76]:
a1

tensor([1., 1., 2.])

In [71]:
a7

functools.partial(<function set_value at 0x7fd8742b9dc0>, index=2, value=2.0)

In [81]:
points0 = client.submit(lambda x: x(6), torch.zeros)
points1 = await client.gather(points0)

In [83]:
values = list(enumerate([4.0, 1.0, 5.0, 3.0, 2.0, 1.0]))

In [85]:
for i, j in values:
    points1[i] = j

In [86]:
points1

tensor([4., 1., 5., 3., 2., 1.])

In [87]:
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [89]:
float(points2[0]), float(points2[1])

(4.0, 1.0)

In [90]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

/Users/thomassullivan/opt/anaconda3/envs/edgemont/lib/python3.9/site-packages/distributed/deploy/spec.py:663: RuntimeWarning: coroutine 'wait_for' was never awaited
  cluster.close(timeout=10)
/Users/thomassullivan/opt/anaconda3/envs/edgemont/lib/python3.9/site-packages/distributed/deploy/spec.py:663: RuntimeWarning: coroutine 'SpecCluster._close' was never awaited
  cluster.close(timeout=10)
